### PR TITLE
Changes time!

### PR DESCRIPTION
**Pull request by cr3pt**
I hope los as the acronym can be OK?

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@everyone

If you didn't know .... LineageOS (previously known as CyanogenMod) doesn't merge pull
requests submitted directly to their LineageOS' repositories.

**Comment by cr3pt** [comment]
So maybe you can share gerrit address? Is gerrit.* or review.* or isn't ready jest?

**Comment by neobuddy89** [comment]
LOS-1.0 ;)

**Comment by YumeMichi** [comment]
@cr3pt Maybe coming soon :lol
https://github.com/LineageOS/www/commit/5cbeb82a785897c3199565af2d6a1d80e857cee1#diff-92752e5e274c7e9111d69bcc46cb144fR6

**Comment by genebean** [comment]
Gerrit is up now: https://review.lineageos.org/#/q/status:open

**Comment by neobuddy89** [comment]
Will LineageOS use same branch names cm-14.1 or change?

**Comment by zxedker** [comment]
#5

**Comment by ItzLevvie** [comment]
@neobuddy89 

"For convenience, and because users won't see it, the source branch name will remain as cm-14.1. We also plan to stick to the current versioning scheme to keep it obvious to our users coming from CM." - @haggertk

**Comment by lineageos-gerrit** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at https://zifnab.net/~zifnab/wiki_dump/Howto:_Gerrit.html

Thanks!

**Pull request closed without merging**
