### PR TITLE
Merge tag 'android-8.1.0_r29'

### PR DESCRIPTION
**Pull request by BunsExynos**
Merge tag 'android-8.1.0_r29' 

Android 8.1.0 Release 29 (OPM4.171019.016.C1)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@BunsExynos Close?

Please submit patches through LineageOS Gerrit

**Comment by migmaq884** [comment]
Can anyone help me root my android 7.1.1 Motorola g4 play?

**Comment by Kduah27** [comment]
When will the next merge tag be released

**Comment by ItzLevvie** [comment]
@Kduah27 There's no need for a "next merge tag".

We're already on android-8.1.0_r43 which contains August 5th security patch.

**Pull request closed without merging**
