### PR TITLE
Staging/lineage 15.1

### PR DESCRIPTION
**Pull request by Rubancv**

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@Rubancv Close?

**Comment by ItzLevvie** [comment]
@Rubancv Close?

Please submit patches through LineageOS Gerrit

**Comment by CurveOS** [comment]
Ping! This should be closed, please.

**Comment by ItzLevvie** [comment]
Hey there, @Rubancv!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Review by alvarogabrielgomez — APPROVED** [review]

**Comment by haggertk** [comment]
Code changes to LineageOS are submitted through Gerrit - https://wiki.lineageos.org/how-to/submitting-patches

**Pull request closed without merging**
