### PR TITLE
Update README.mkdn

### PR DESCRIPTION
**Pull request by Silvered99**
Switch to CyanogenMod to Lineage OS

### CODE REVIEW

**Comment by olegsvs** [comment]
Maybe rename branch?

**Comment by Silvered99** [comment]
Yes

**Comment by ItzLevvie** [comment]
Close the issue..

**Comment by ItzLevvie** [comment]
@everyone

If you didn't know .... LineageOS (previously known as CyanogenMod) doesn't merge pull
requests submitted directly to their LineageOS' repositories.

**Pull request closed without merging**
